#!/usr/bin/env python3

#local = "http://localhost:8081/"
#tpvs = "https://www.tpvs.hmrc.gov.uk/HMRC/CT600"
#ets = "https://test-transaction-engine.tax.service.gov.uk/submission"

############################################################################

from gnucash_uk_corptax.govtalk import *
from gnucash_uk_corptax.corptax import *

import xml.etree.ElementTree as ET
import asyncio
import aiohttp
import time
import xml.dom.minidom
import sys
import json

if len(sys.argv) != 4:
    print("Usage:\n\tcli <config> <accts> <comps>\n")
    sys.exit(1)

params = json.loads(open(sys.argv[1]).read())
accts = open(sys.argv[2]).read()
comps = open(sys.argv[3]).read()

ret = to_return(comps, accts, params)

utr = ret.find(".//{%s}Reference" % ct_ns).text

req = GovTalkSubmissionRequest({
    "username": params["username"],
    "password": params["password"],
    "class": "HMRC-CT-CT600",
    "gateway-test": params["gateway-test"],
    "tax-reference": utr,
    "vendor-id": params["vendor-id"],
    "software": params["software"],
    "software-version": params["software-version"],
    "ir-envelope": ret.getroot()
})

print("IRmark is", req.get_irmark())

req.add_irmark()

async def call(req, ep):

    async with aiohttp.ClientSession() as session:

        data = req.toxml()

        async with session.post(ep, data=data) as resp:
            if resp.status != 200:
                raise RuntimeError(
                    "Transaction failed: status=%d" % resp.status
                )
            data = await resp.text()

            msg = GovTalkMessage.decode(data)

            if isinstance(msg, GovTalkSubmissionError):
                raise RuntimeError(msg.get("error-text"))

            return msg

async def submit(req):

    resp = await call(req, params["url"])

    correlation_id = resp.get("correlation-id")
    endpoint = resp.get("response-endpoint")
    poll = float(resp.get("poll-interval"))

    print("Correlation ID is", correlation_id)
    print("Endpoint is", endpoint)
    print("Poll time is", poll)

    timeout = time.time() + 20
    
    while True:

        if time.time() > timeout:
            raise RuntimeError("Timeout waiting for valid response.")

        await asyncio.sleep(poll)

        req = GovTalkSubmissionPoll({
	    "username": params["username"],
	    "password": params["password"],
	    "class": "HMRC-CT-CT600",
	    "gateway-test": params["gateway-test"],
            "correlation-id": correlation_id
        })

        print("Poll...")
        resp = await call(req, endpoint)

        correlation_id = resp.get("correlation-id")
        endpoint = resp.get("response-endpoint")
        poll = float(resp.get("poll-interval"))

        if isinstance(resp, GovTalkSubmissionResponse):
            break

    print("Submitted successfully.")

    req = GovTalkDeleteRequest({
	"username": params["username"],
	"password": params["password"],
	"class": "HMRC-CT-CT600",
	"gateway-test": params["gateway-test"],
        "correlation-id": correlation_id
    })

    print("Delete request...")
    resp = await call(req, endpoint)

    print("Completed.")

try:
    loop = asyncio.get_event_loop()
    loop.run_until_complete(submit(req))
except Exception as e:
    print("Exception:", str(e))

